### ISSUE TITLE
It's time to move on

### ISSUE THREAD

**Issue by DerGoogler** [Magisk-Modules-Alt-Repo/json#14]
Hey guys,

it's time to move on and migrate to a new repo format. FoxMMM is dead and I see not nothing good in the upcoming AMM update — v3, probably not open source anymore.

@Atrate, currently is the repo from MMAR not browsable in MMRL ([commit](https://github.com/Magisk-Modules-Alt-Repo/submission/commit/d967d9c441473ec80d131093f797d15989d744cf))

The new (beta) MRepo repo format lacks of good features like `icon`, `readme`, `antifeatures` and many more. I've forked the [magisk-repo-util](https://github.com/Googlers-Repo/magisk-modules-repo-util) long time ago and proved a good usage in MMRL.

I would continue to migrate repositories to here and then add them to the repo — even when you can add externals, keeping them in this repo offers a better maintenance.

Any objections? Let me know!

@Atrate @tytydraco @HuskyDG

**Comment by Atrate** [comment]
If I understand you correctly, you propose a new modules.json format. If you want, you can just make a `Magisk-Modules-Alt-Repo/json2` repo (or name it some other way you see fit) and keep the new format there, there's no problem with us having both running concurrently.

**Comment by DerGoogler** [comment]
This is also an option
