### ISSUE TITLE
SQLite3-Universal-Binaries module not downloading files

### ISSUE THREAD

**Issue by stylemessiah** [Magisk-Modules-Alt-Repo/json#2]
Had 4 repos added today, only this one fails to download and install the module

**Comment by tytydraco** [comment]
Oh boy, this one's wacky. Have you tried just downloading the zip from online and installing it? This would indicate a module issue, not a JSON issue.

**Comment by stylemessiah** [comment]
> Oh boy, this one's wacky. Have you tried just downloading the zip from online and installing it? This would indicate a module issue, not a JSON issue.

This was  wacky one, i finally traced it down to some sort on encoding issue on the module.prop file, must have corrupted in migration...fun times because that mofule had worked for years and over 3k downloads

Should be all workies now :)
